Refactor instruction structures.
second-state/SSVM pull request #122
Opened 2020-12-22 13:41 UTC by q82419

1. Merge all instruction nodes.
2. Use vector of instance instead of vector of unique pointers in all AST nodes.
3. Apply proposal configurations checking loader and validation phases.
4. Refactor validator, interpreter, and compiler for new instruction structures.
5. Update store manager to support program counter.
6. Refine the logging for cleaner code.
7. Update AST tests.

2020-12-23 08:27 UTC, hydai requested changes

2020-12-23 08:27 UTC, hydai commented on lib/ast/segment.cpp
> +/// TODO
?

2020-12-23 08:45 UTC, q82419 commented on include/interpreter/engine/binary_numeric.ipp
> +                                           const uint32_t Index) const {
We use `uint32_t TargetIndex` instead of `uint8_t LaneIndex`.

2020-12-23 08:45 UTC, q82419 commented on include/interpreter/engine/unary_numeric.ipp
> +                                           const uint32_t Index) const {
We use `uint32_t TargetIndex` instead of `uint8_t LaneIndex`.

2020-12-24 06:11 UTC, hydai approved these changes

2020-12-24 06:18 UTC, hydai approved these changes

2020-12-24 07:15 UTC, merged