Merge the configurations and cost table.
second-state/SSVM pull request #154
Opened 2021-01-28 20:10 UTC by q82419

1. Merge the proposal configurations and the pre-register host functions configurations.
2. Merge the cost table into statistics.

2021-01-31 15:46 UTC, hydai requested changes

2021-01-31 16:04 UTC, q82419 commented on include/common/statistics.h
> +      : CostTab(UINT16_MAX + 1, 1ULL), InstrCnt(0), CostLimit(Lim), CostSum(0) {
The deleted `costtable.h` used `1` as initial instruction costs in every types. Only the `ssvm-evmc` set as 0 in `Statistics` class.
If you think `0` is ok, we can set `0` in initial cost table.

2021-02-01 07:52 UTC, hydai commented on include/common/statistics.h
> +      : CostTab(UINT16_MAX + 1, 1ULL), InstrCnt(0), CostLimit(Lim), CostSum(0) {
Got it. `1` is fine for me.

2021-02-01 09:33 UTC, hydai approved these changes

2021-02-01 09:40 UTC, merged