Add SSVM C API and tests.
second-state/SSVM pull request #173
Opened 2021-02-25 17:58 UTC by q82419

1. Add SSVM C API and shared library.
2. Add SSVM C API tests.
3. Refactor spec test class.

2021-03-23 09:31 UTC, q82419 commented
TODO: Add type checking of parameters when invoking functions.

2021-03-26 11:49 UTC, ibmibmibm requested changes

2021-03-26 11:49 UTC, ibmibmibm commented on lib/interpreter/interpreter.cpp
> +    GotParamTypes.assign(Params.size() - GotParamTypes.size(), ValType::I32);
`assign` 會清掉內容，這邊應該用resize吧，然後後面也可以改用resize，就可以用同樣一行程式
`GotParamTypes.resize(Params.size(), ValType::I32);`
所以上面的`if`就可以刪掉了

2021-03-26 11:49 UTC, ibmibmibm commented on lib/interpreter/interpreter.cpp
> +    GotParamTypes.assign(Params.size() - GotParamTypes.size(), ValType::I32);
還是你這邊只是要顯示錯誤訊息，那應該不用調整`GotParamTypes`的內容吧

2021-03-26 12:14 UTC, q82419 commented
The issues above fixed in [PR177](https://github.com/second-state/SSVM/pull/177) and rebased.

2021-04-12 08:47 UTC, ibmibmibm commented on lib/interpreter/interpreter.cpp
> +    if (Res.error() != ErrCode::Terminated) {
為什麼這邊要特例避開Terminated?

2021-04-12 08:47 UTC, ibmibmibm commented on lib/api/ssvm.cpp
> +  return toFTypeCxt(Cxt);
這個function未定義?

2021-04-12 08:47 UTC, ibmibmibm commented on lib/api/ssvm.cpp
> +    return toHostFuncCxt(
這個function未定義?

2021-04-13 03:30 UTC, q82419 commented on lib/api/ssvm.cpp
> +    return toHostFuncCxt(
Defined in macro.

2021-04-13 03:30 UTC, q82419 commented on lib/api/ssvm.cpp
> +  return toFTypeCxt(Cxt);
Defined in macro.

2021-04-13 03:31 UTC, q82419 commented on lib/interpreter/interpreter.cpp
> +    if (Res.error() != ErrCode::Terminated) {
Fixed in the tools.

2021-04-14 14:20 UTC, hydai approved these changes

2021-04-14 14:37 UTC, ibmibmibm commented on lib/api/ssvm.cpp
> +
這邊應該多一個產生string_view的版本
```
inline std::string_view genStrView(const SSVM_String S) noexcept {
  return std::string_view(S.Buf, S.Length);
}
```

2021-04-14 14:37 UTC, ibmibmibm commented on lib/api/ssvm.cpp
> +inline std::string genStr(const SSVM_String S) noexcept {
string constructor有可能丟出bad_alloc

2021-04-14 14:37 UTC, ibmibmibm commented on lib/api/ssvm.cpp
> +      : ImportObject(genStr(ModName)), Data(Ptr) {}
改用`genStrView`

2021-04-14 14:37 UTC, ibmibmibm commented on lib/api/ssvm.cpp
> +      const auto FuncIter = FuncExp.find(genStr(FuncName));
改用`genStrView`

2021-04-14 14:37 UTC, ibmibmibm commented on lib/api/ssvm.cpp
> +    if (auto Res = fromStoreCxt(Cxt)->findModule(genStr(ModuleName))) {
改用`genStrView`

2021-04-14 14:37 UTC, ibmibmibm commented on lib/api/ssvm.cpp
> +    if (auto Res = fromStoreCxt(Cxt)->findModule(genStr(ModuleName))) {
改用`genStrView`

2021-04-15 07:02 UTC, ibmibmibm approved these changes

2021-04-15 14:12 UTC, merged