Add SSVM_Process mode and ssvm_process host modules.
second-state/SSVM pull request #59
Opened 2020-08-28 10:35 UTC by q82419

2020-08-28 16:14 UTC, hydai requested changes

2020-08-31 05:54 UTC, q82419 commented on lib/host/ssvm_process/processfunc.cpp
> +  Env.Args.push_back(std::move(NewArg));
Sure.

2020-08-31 05:55 UTC, q82419 commented on include/vm/costtable.h
> -      /// Wasm cost table
In the current state, we don't need a cost table. This is preserved for future using.

2020-08-31 05:55 UTC, q82419 commented on include/vm/costtable.h
> -      /// Wasi cost table
In the current state, we don't need a cost table. This is preserved for future using.

2020-08-31 05:56 UTC, q82419 commented on include/vm/costtable.h
> +    if (Table.size() < UINT16_MAX) {
I think this work can be done when refactoring in the future.

2020-08-31 05:57 UTC, q82419 commented on lib/vm/vm.cpp
> +    Measure.setCostTable(CostTab.getCostTable(Configure::VMType::SSVM_Process));
The highest priority of the cost table will be set into measurement class.

2020-08-31 05:59 UTC, q82419 commented on lib/vm/vm.cpp
> +    /// 2st priority of cost table: Wasi
The ideal priority will be:
 1. SSVM_Process
 2. wasi
 3. wasm

2020-08-31 06:21 UTC, hydai commented on include/vm/costtable.h
> -      /// Wasm cost table
If we don't initialize the cost table, what will happen when we try to get the runtime cost?

2020-08-31 06:21 UTC, hydai commented on include/vm/costtable.h
> -      /// Wasi cost table
Ditto.

2020-08-31 06:21 UTC, hydai commented on include/vm/costtable.h
> +    if (Table.size() < UINT16_MAX) {
Okay.

2020-08-31 06:24 UTC, hydai requested changes

2020-08-31 06:24 UTC, hydai commented on lib/host/ssvm_process/processfunc.cpp
> +  Env.Args.push_back(std::move(NewArg));
How about using `AddArg` or `AppendArg`?

2020-08-31 06:24 UTC, hydai commented on lib/vm/vm.cpp
> +    Measure.setCostTable(CostTab.getCostTable(Configure::VMType::SSVM_Process));
Why does the 1st priority be initiated after the 2nd priority?

2020-08-31 06:25 UTC, hydai commented on lib/vm/vm.cpp
> +    /// 2st priority of cost table: Wasi
Okay

2020-08-31 09:59 UTC, q82419 commented on lib/vm/vm.cpp
> +    Measure.setCostTable(CostTab.getCostTable(Configure::VMType::SSVM_Process));
If 1st priority is initiated before the 2nd priority, the cost table will be overridden when satisfying with the condition of the 2nd priority.

2020-08-31 10:07 UTC, hydai commented on lib/vm/vm.cpp
> +    Measure.setCostTable(CostTab.getCostTable(Configure::VMType::SSVM_Process));
If I enable multiple VMType (Wasi+SSVM_Process) at the same time, will the cost calculate correctly?
You said that the cost table will be overridden.
Assume I have:
1) Instruction A in Wasi, cost 100
2) Instruction B in SSVM_Process, cost 200

When I call A, the final cost will be 100.
When I call A+B, what's the final cost? Can it found the instruction cost after its cost table is overridden?

2020-08-31 10:07 UTC, q82419 commented on include/vm/costtable.h
> -      /// Wasm cost table
In this case, the cost table of `VMType::Wasm` will be returned.
I've updated to add default `Wasm` cost table in the constructor.

2020-08-31 10:07 UTC, q82419 commented on include/vm/costtable.h
> -      /// Wasi cost table
Ditto.

2020-08-31 10:07 UTC, q82419 commented on lib/host/ssvm_process/processfunc.cpp
> +  Env.Args.push_back(std::move(NewArg));
Updated.

2020-08-31 10:10 UTC, q82419 commented on lib/vm/vm.cpp
> +    Measure.setCostTable(CostTab.getCostTable(Configure::VMType::SSVM_Process));
The final cost will be 200.
The cost table priority will be `SSVM_Process` > `Wasi` > `Wasm`.

2020-08-31 10:22 UTC, hydai commented on lib/vm/vm.cpp
> +    Measure.setCostTable(CostTab.getCostTable(Configure::VMType::SSVM_Process));
Ah-ha, I got it.
The cost table only contains the wasm instructions from wasm spec, not including the host functions part.

2020-09-01 13:50 UTC, hydai approved these changes

2020-09-01 13:50 UTC, merged