Implement WASM bulk memory operation and reference types proposals
second-state/SSVM pull request #77
Opened 2020-10-14 11:08 UTC by q82419

1. Add data count dection.
2. New definition of `numtype` and `reftype`.
3. Update error code definitions.
4. Apply new version of `data segment` and `element segment`.
5. Add new bulk memory operation and reference type instructions.
  a. Reference instructions:
    * ref.null
    * ref.is_null
    * ref.func
  b. Table instructions:
    * table.get
    * table.set
    * table.init
    * elem.drop
    * table.copy
    * table.grow
    * table.size
    * table.fill
  c. Memory instructions:
    * memory.init
    * data.drop
    * memory.copy
    * memory.fill
  d. Parametric instructions:
    * select t
6. Update validator for data and element contexts.
7. Refactor runtime structure for supporting data and element instances.
8. Use WASM spec test suite for reference types.
9. Add document about using `externref`.

2020-10-14 12:44 UTC, hydai requested changes

2020-10-14 12:44 UTC, hydai commented on lib/ast/instruction.cpp
> +    // fall through
`[[fallthrough]];`

2020-10-14 13:23 UTC, q82419 commented on lib/ast/instruction.cpp
> +    // fall through
Done.

2020-10-15 12:11 UTC, hydai requested changes

2020-10-16 03:12 UTC, q82419 commented on include/runtime/instance/table.h
> +  bool growTable(const uint32_t Count, const ValVariant Val) {
Done.

2020-10-16 03:42 UTC, hydai requested changes

2020-10-16 03:42 UTC, hydai commented on Changelog.md
> +* Completed the enumeration value checking in loading phase.
in `the` loading phase.

2020-10-16 03:42 UTC, hydai commented on Changelog.md
> +* Updated error codes according to test suite for the reference types proposal.
to `the` test suite...

2020-10-16 08:29 UTC, hydai approved these changes
LGTM

2020-10-16 08:33 UTC, merged